name: Example

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Load mysql:8.0
    runs-on: ubuntu-latest
    steps:
      - uses: YumaFuu/public-docker-image-cache-action@v1
        with:
          image: mysql:8.0

      - run: echo "Done"
